/*
Author: Cassie Lewis
https://clewisdev.com
Date: March 2023 
*/

/****** VARIABLES ******/

//TODO NUMBERS CONTAINER

//TODO SEND BUTTON

//TODO RESET BUTTON

/****** FUNCTIONS ******/

//TODO PULL NUMBER BUTTONS VIA EVENT DELEGATION AND DATASETS

//TODO DISPLAY IN "PHONE" DISPLAY

//TODO SEND TO "PAGER DISPLAY"


/****** EVENT LISTENERS ******/

//TODO EVENTLISTENER NUMBERS CONTAINER

//TODO EVENTLISTENER SEND BUTTON

//TODO EVENT LISTENER RESET BUTTON